insert into merchant(merchant_id, merchant_name) values (11, 'RR Diner');
insert into merchant(merchant_id, merchant_name) values (12, 'Big Kahuna Burger');
insert into merchant(merchant_id, merchant_name) values (13, 'Good Burger');
insert into merchant(merchant_id, merchant_name) values (14, 'Stan Mikitas All Star Cafe');
insert into merchant(merchant_id, merchant_name) values (15, 'Cheers');
insert into merchant(merchant_id, merchant_name) values (16, 'McDowells');
insert into merchant(merchant_id, merchant_name) values (17, 'The Max');
insert into merchant(merchant_id, merchant_name) values (18, 'Krusty Burger');
insert into merchant(merchant_id, merchant_name) values (19, 'Nuovo Vesuvio');
insert into merchant(merchant_id, merchant_name) values (20, 'Bronto Burger');
